name: 'Slack Summary'
description: 'Posts a Slack message with a summary of the current workflow'
author: "Lewis O'Driscoll"
inputs:
  github-token:
    description: 'Actions token (secrets.GITHUB_TOKEN)'
    required: true
  slack-webhook-url:
    description: 'Slack webhook URL for sending messages'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
